// {
//     "tableState": {
//         "table_color": "#EF5350",
//         "table_action_flag": 2
//     },
//     "bill_number": "9a0gprv4FAOFySS8846",
//     "payid": 0,
//     "kot_id": 32,
//     "order_id": 11,
//     "payment_mode": "Cash",
//     "charges": [],
//     "noofPersons": 1,
//     "customerName": "",
//     "customerMobile": "",
//     "ebillCheckstat": 1,
//     "showonBillstat": 1,
//     "discount_type": null,
//     "discount": null,
//     "billItems": [
//         {
//             "kot_items_id": 127,
//             "title": "SS",
//             "amount": 0.42,
//             "quantity": 1,
//             "item_id": 823933,
//             "item_price": 0.424,
//             "item_tax_per": 5,
//             "item_tax_value": 0.02,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "3",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0.424,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 0.456,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 128,
//             "title": "CHICKEN FRIED RICE",
//             "amount": 186,
//             "quantity": 2,
//             "item_id": 823932,
//             "item_price": 93,
//             "item_tax_per": 5,
//             "item_tax_value": 4.43,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "2",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 93,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 100,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 129,
//             "title": "Chicken Fried Rice",
//             "amount": 46.5,
//             "quantity": 1,
//             "item_id": 823931,
//             "item_price": 46.5,
//             "item_tax_per": 5,
//             "item_tax_value": 2.21,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "1",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 46.5,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 50,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 130,
//             "title": "SHREDDED PANEER NACHO'S",
//             "amount": 101.37,
//             "quantity": 1,
//             "item_id": 714992,
//             "item_price": 101.37,
//             "item_tax_per": 5,
//             "item_tax_value": 4.83,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME175",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 101.37,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 109,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 131,
//             "title": "dec",
//             "amount": 66,
//             "quantity": 6,
//             "item_id": 1331074,
//             "item_price": 11,
//             "item_tax_per": 5,
//             "item_tax_value": 0.52,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "0.22",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 0,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 11,
//             "modified_discount": 0,
//             "kitchen_dept": 7288,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "Addons",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 132,
//             "title": "LOADED CHEESE MEXICANA NACHOS",
//             "amount": 129.27,
//             "quantity": 1,
//             "item_id": 714993,
//             "item_price": 129.27,
//             "item_tax_per": 5,
//             "item_tax_value": 6.16,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME176",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 129.27,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 139,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 133,
//             "title": "PLAIN NACHOS WITH SALSA",
//             "amount": 64.17,
//             "quantity": 1,
//             "item_id": 714990,
//             "item_price": 64.17,
//             "item_tax_per": 5,
//             "item_tax_value": 3.06,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME173",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 64.17,
//             "discount_type": 1,
//             "discount_rate": 7,
//             "pricebeforeDiscount": 69,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NACHO'S",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 134,
//             "title": "CHAIOPS SIGNATURE  CHAI -20",
//             "amount": 19,
//             "quantity": 1,
//             "item_id": 714828,
//             "item_price": 19,
//             "item_tax_per": 5,
//             "item_tax_value": 0.91,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME11",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 19,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": "[{\"to\":\"23:59\",\"from\":\"00:01\",\"on_qty\":1,\"get_qty\":1,\"discount_id\":3688,\"itemmustBuy\":\"714827,714828\",\"item_id_list\":714829,\"discount_name\":\"BG1\",\"percentage_off\":100,\"has_restrictions\":false}]",
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 135,
//             "title": "PLAIN COFFEE",
//             "amount": 0,
//             "quantity": 1,
//             "item_id": 714829,
//             "item_price": 0,
//             "item_tax_per": 5,
//             "item_tax_value": 0,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME12",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 100,
//             "pricebeforeDiscount": 29,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": "{\"to\":null,\"from\":null,\"on_qty\":1,\"get_qty\":1,\"discount_id\":3700,\"itemmustBuy\":714829,\"item_id_list\":714841,\"discount_name\":\"BG5\",\"percentage_off\":50,\"has_restrictions\":false}",
//             "discount_name": "BG1",
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 136,
//             "title": "CHOCOLATE  CHAI",
//             "amount": 19,
//             "quantity": 1,
//             "item_id": 714826,
//             "item_price": 19,
//             "item_tax_per": 5,
//             "item_tax_value": 0.91,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME9",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 19,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 137,
//             "title": "ROSE  CHAI",
//             "amount": 15,
//             "quantity": 1,
//             "item_id": 714825,
//             "item_price": 15,
//             "item_tax_per": 5,
//             "item_tax_value": 0.71,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME8",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 15,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 35,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 138,
//             "title": "PAAN CHAI",
//             "amount": 19,
//             "quantity": 1,
//             "item_id": 714824,
//             "item_price": 19,
//             "item_tax_per": 5,
//             "item_tax_value": 0.91,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME7",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 19,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 139,
//             "title": "KADAK CHAI",
//             "amount": 30,
//             "quantity": 1,
//             "item_id": 714821,
//             "item_price": 30,
//             "item_tax_per": 5,
//             "item_tax_value": 1.43,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME4",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 30,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 140,
//             "title": "ADRAK CHAI",
//             "amount": 5,
//             "quantity": 1,
//             "item_id": 714822,
//             "item_price": 5,
//             "item_tax_per": 5,
//             "item_tax_value": 0.24,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME5",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 5,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 25,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 141,
//             "title": "STRAWBERRY CHAI",
//             "amount": 19,
//             "quantity": 1,
//             "item_id": 714823,
//             "item_price": 19,
//             "item_tax_per": 5,
//             "item_tax_value": 0.91,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME6",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 19,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 142,
//             "title": "ELACHI   CHAI",
//             "amount": 5,
//             "quantity": 1,
//             "item_id": 714820,
//             "item_price": 5,
//             "item_tax_per": 5,
//             "item_tax_value": 0.24,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME3",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 5,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 25,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 143,
//             "title": "BOMBAY CUTTING  CHAI",
//             "amount": 40,
//             "quantity": 2,
//             "item_id": 714819,
//             "item_price": 20,
//             "item_tax_per": 5,
//             "item_tax_value": 0.95,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME2",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 2,
//             "discount_rate": 20,
//             "pricebeforeDiscount": 20,
//             "modified_discount": 1,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "KULHAD TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 144,
//             "title": " MENGO FRUITY SMOOTHIE",
//             "amount": 238,
//             "quantity": 2,
//             "item_id": 714840,
//             "item_price": 119,
//             "item_tax_per": 5,
//             "item_tax_value": 5.67,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME23",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 119,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "SMOOTHIES",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 145,
//             "title": "BERRY BLAST SMOOTHIE",
//             "amount": 238,
//             "quantity": 2,
//             "item_id": 714839,
//             "item_price": 119,
//             "item_tax_per": 5,
//             "item_tax_value": 5.67,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME22",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 119,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "SMOOTHIES",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 146,
//             "title": "shawarma",
//             "amount": 2,
//             "quantity": 1,
//             "item_id": 1354773,
//             "item_price": 2,
//             "item_tax_per": 5,
//             "item_tax_value": 0.1,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "SB6",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 2,
//             "modified_discount": 0,
//             "kitchen_dept": 7288,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "al  sh",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 147,
//             "title": "HAZELNUT COFFEE",
//             "amount": 59,
//             "quantity": 1,
//             "item_id": 714838,
//             "item_price": 59,
//             "item_tax_per": 5,
//             "item_tax_value": 2.81,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME21",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 59,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 148,
//             "title": "TURMERIC LATTE ",
//             "amount": 59,
//             "quantity": 1,
//             "item_id": 714835,
//             "item_price": 59,
//             "item_tax_per": 5,
//             "item_tax_value": 2.81,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME18",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 59,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 149,
//             "title": "CAFÉ CARAMEL",
//             "amount": 59,
//             "quantity": 1,
//             "item_id": 714834,
//             "item_price": 59,
//             "item_tax_per": 5,
//             "item_tax_value": 2.81,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME17",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 59,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 150,
//             "title": "HOT CHOCLATE",
//             "amount": 59,
//             "quantity": 1,
//             "item_id": 714837,
//             "item_price": 59,
//             "item_tax_per": 5,
//             "item_tax_value": 2.81,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME20",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 59,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 151,
//             "title": "CAPPUCCINO ",
//             "amount": 39,
//             "quantity": 1,
//             "item_id": 714831,
//             "item_price": 39,
//             "item_tax_per": 5,
//             "item_tax_value": 1.86,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME14",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 152,
//             "title": "CAFÉ MOCHA",
//             "amount": 59,
//             "quantity": 1,
//             "item_id": 714833,
//             "item_price": 59,
//             "item_tax_per": 5,
//             "item_tax_value": 2.81,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME16",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 59,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "HOT COFFEE",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 153,
//             "title": "FUSILLI ALFREDO",
//             "amount": 149,
//             "quantity": 1,
//             "item_id": 714848,
//             "item_price": 149,
//             "item_tax_per": 5,
//             "item_tax_value": 7.09,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME31",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 149,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "PASTA / MACARONI",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 154,
//             "title": "SPAGHETTI/penne MUSHROOM ",
//             "amount": 159,
//             "quantity": 1,
//             "item_id": 714850,
//             "item_price": 159,
//             "item_tax_per": 5,
//             "item_tax_value": 7.57,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME33",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 159,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "PASTA / MACARONI",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 155,
//             "title": "SPAGHETTI/penne MIX SAUCES",
//             "amount": 149,
//             "quantity": 1,
//             "item_id": 714849,
//             "item_price": 149,
//             "item_tax_per": 5,
//             "item_tax_value": 7.09,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME32",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 149,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "PASTA / MACARONI",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 156,
//             "title": "FUSILLI ARABIATA",
//             "amount": 119,
//             "quantity": 1,
//             "item_id": 714846,
//             "item_price": 119,
//             "item_tax_per": 5,
//             "item_tax_value": 5.67,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME29",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 119,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": "[{\"to\":\"23:59\",\"from\":\"00:01\",\"on_qty\":1,\"get_qty\":1,\"discount_id\":3696,\"itemmustBuy\":714846,\"item_id_list\":714914,\"discount_name\":\"BG3\",\"percentage_off\":50,\"has_restrictions\":false}]",
//             "discount_name": null,
//             "category_name": "PASTA / MACARONI",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 157,
//             "title": "MANGO SHAKE",
//             "amount": 49.5,
//             "quantity": 1,
//             "item_id": 714914,
//             "item_price": 49.5,
//             "item_tax_per": 5,
//             "item_tax_value": 2.36,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME97",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 49.5,
//             "discount_type": 1,
//             "discount_rate": 50,
//             "pricebeforeDiscount": 99,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": "BG3",
//             "category_name": "SHAKES",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 158,
//             "title": "SPICY VEGGY MACRONI",
//             "amount": 139,
//             "quantity": 1,
//             "item_id": 714847,
//             "item_price": 139,
//             "item_tax_per": 5,
//             "item_tax_value": 6.62,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME30",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 139,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "PASTA / MACARONI",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 159,
//             "title": "CHAIOPS SIGNATURE Khullad PIZZA + cold coffee ",
//             "amount": 199,
//             "quantity": 1,
//             "item_id": 714908,
//             "item_price": 199,
//             "item_tax_per": 5,
//             "item_tax_value": 9.48,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME91",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 199,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 160,
//             "title": "PANEER KURKURE MOMOS (6PCS) +ice tea",
//             "amount": 149,
//             "quantity": 1,
//             "item_id": 714911,
//             "item_price": 149,
//             "item_tax_per": 5,
//             "item_tax_value": 7.09,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME94",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 149,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 161,
//             "title": "special mom's veggy MAGGi +cold coffee",
//             "amount": 139,
//             "quantity": 1,
//             "item_id": 714910,
//             "item_price": 139,
//             "item_tax_per": 5,
//             "item_tax_value": 6.62,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME93",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 139,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 162,
//             "title": "Grilled Corn Sandwich +CLASSIC MOJITO",
//             "amount": 139,
//             "quantity": 1,
//             "item_id": 714907,
//             "item_price": 139,
//             "item_tax_per": 5,
//             "item_tax_value": 6.62,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME90",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 139,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 163,
//             "title": "BUY 2 MEDIUM PIZZA GET 1 SMALL PIZZA FREE",
//             "amount": 399,
//             "quantity": 1,
//             "item_id": 714904,
//             "item_price": 399,
//             "item_tax_per": 5,
//             "item_tax_value": 19,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME87",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 399,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 164,
//             "title": "Garlic Cheese Bread + chocolate chai",
//             "amount": 99,
//             "quantity": 1,
//             "item_id": 714905,
//             "item_price": 99,
//             "item_tax_per": 5,
//             "item_tax_value": 4.71,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME88",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 99,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 165,
//             "title": "VEG  CHEESE BURGER+Masala FRENCH FRIES+ice tea",
//             "amount": 189,
//             "quantity": 1,
//             "item_id": 714902,
//             "item_price": 189,
//             "item_tax_per": 5,
//             "item_tax_value": 9,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME85",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 189,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 166,
//             "title": "VANILA SHAKE + PLAIN NACHOS",
//             "amount": 149,
//             "quantity": 1,
//             "item_id": 714901,
//             "item_price": 149,
//             "item_tax_per": 5,
//             "item_tax_value": 7.09,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME84",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 149,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "COMBOS OFFERS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 167,
//             "title": "CHOCOLATE FANTACY SUNDAE",
//             "amount": 139,
//             "quantity": 1,
//             "item_id": 714924,
//             "item_price": 139,
//             "item_tax_per": 5,
//             "item_tax_value": 6.62,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME107",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 139,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "DESSERT & PASTRY",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 168,
//             "title": "CHOCLATE CAKE SUNDAE",
//             "amount": 119,
//             "quantity": 1,
//             "item_id": 714923,
//             "item_price": 119,
//             "item_tax_per": 5,
//             "item_tax_value": 5.67,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME106",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 119,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "DESSERT & PASTRY",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 169,
//             "title": "devil sin brownie with ice cream",
//             "amount": 89,
//             "quantity": 1,
//             "item_id": 714926,
//             "item_price": 89,
//             "item_tax_per": 5,
//             "item_tax_value": 4.24,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME109",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 89,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "DESSERT & PASTRY",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 170,
//             "title": "HIMALAYAN ORTHODEX",
//             "amount": 39,
//             "quantity": 1,
//             "item_id": 714945,
//             "item_price": 39,
//             "item_tax_per": 5,
//             "item_tax_value": 1.86,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME128",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NON MILK BASE TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 171,
//             "title": "AROMATIC TULSI TURMERIC TEA",
//             "amount": 39,
//             "quantity": 1,
//             "item_id": 714944,
//             "item_price": 39,
//             "item_tax_per": 5,
//             "item_tax_value": 1.86,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME127",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NON MILK BASE TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 172,
//             "title": "DARJELLING  TEA",
//             "amount": 35,
//             "quantity": 1,
//             "item_id": 714941,
//             "item_price": 35,
//             "item_tax_per": 5,
//             "item_tax_value": 1.67,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME124",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 35,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NON MILK BASE TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 173,
//             "title": "HEALTHY GREEN TEA SUPER FINE",
//             "amount": 39,
//             "quantity": 1,
//             "item_id": 714940,
//             "item_price": 39,
//             "item_tax_per": 5,
//             "item_tax_value": 1.86,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME123",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "NON MILK BASE TEA",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         },
//         {
//             "kot_items_id": 174,
//             "title": "MOZZARELLA CHEESE",
//             "amount": 39,
//             "quantity": 1,
//             "item_id": 714983,
//             "item_price": 39,
//             "item_tax_per": 5,
//             "item_tax_value": 1.86,
//             "item_tax_method": 1,
//             "item_is_devidable": 0,
//             "item_tax_name": "Tax",
//             "short_code": "ME166",
//             "note": null,
//             "has_options": 0,
//             "product_group_id": 8928,
//             "product_group_name": "Foood",
//             "discounted_price": 0,
//             "discount_type": 1,
//             "discount_rate": 0,
//             "pricebeforeDiscount": 39,
//             "modified_discount": 0,
//             "kitchen_dept": 6695,
//             "kot_id": 32,
//             "hsn_code": null,
//             "is_open_item": 0,
//             "discounted_items": null,
//             "discount_name": null,
//             "category_name": "Add-ons ITEMS",
//             "createdBy": "ter1",
//             "user_id": "ter1"
//         }
//     ],
//     "table_id": "42537",
//     "note": "",
//     "deliveryboy_id": 0,
//     "couponDisount": 0,
//     "couponDisounttype": 0,
//     "coupon": null,
//     "billDetails": {
//         "hasDuepayment": 0,
//         "due_payment": 0,
//         "cust_paid_amount": 4341,
//         "extra_details": "{\"inclusive_tax\":206.729,\"tax\":[{\"name\":\"Tax\",\"tax_percent\":5,\"amount\":206.729,\"tax_inclusive\":true,\"section\":\"Foood\",\"taxDivided\":false}],\"roundedAmount\":-0.23,\"totalCharges\":0,\"invoiceType\":\"B2C\",\"previous_order_id\":\"9a0gp6aaY6jqyGV2323\",\"order_number\":11}",
//         "payment": "Cash",
//         "instructions": "",
//         "id": 12,
//         "isBillModified": 1,
//         "print_status": 0,
//         "draftprint_status": 0,
//         "order_total": 4341,
//         "payment_modes": [
//             {
//                 "id": 13,
//                 "order_id": "9a0gprv4FAOFySS8846",
//                 "payment_option": "Cash",
//                 "amount": 4341,
//                 "status_flag": 0
//             }
//         ]
//     },
//     "kotcreatedAt": 1686382003536,
//     "waiter": null,
//     "waiter_id": 0,
//     "discounted_product_groups": null,
//     "discountTitle": null,
//     "is_pre_order": 0,
//     "custom_bill_number": "SB00011",
//     "createdBy": "ter1",
//     "field1": null,
//     "draftprint_status": 0,
//     "remoteKot": false,
//     "remote_order_id": "0",
//     "kot_numbers": [
//         3
//     ],
//     "kot_status": [
//         1
//     ],
//     "bill_id": 12,
//     "status": 200
// }